### ISSUE TITLE
Review `font-named-instance` `@font-face` property

### ISSUE THREAD

**Issue by ntwb** [WordPress/twentytwenty#409]
I've not come upon `font-named-instance` `@font-face` property before, but what I'm led to believe is the following:

> If `font-named-instanced` is supported, this will be set in `Inter var Regular`, otherwise it will be in `Inter var` for the first example below.

> If `font-named-instanced` is supported, this will be set in `Inter var Italic`, otherwise it will be in `Inter var` for the second example below.

I see no references to `font-named-instance` in:
> https://caniuse.com/#search=font-named-instance
> https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face
> https://drafts.csswg.org/css-fonts-3/#font-face-rule

I see it is proposed for CSS 4:
> https://drafts.csswg.org/css-fonts-4/#font-named-instance

I also couldn't find a PostCSS plugin that supports `font-named-instance`

I don't think removing the `font-named-instance` property from the instances below will have any affect as both declare the `font-style` on the preceeding line, as such I suggest we remove each instance of the `font-named-instance` property from `style.css` below.

----

• `365:2   ✖  Unexpected unknown property property-no-unknown "font-named-instance"`

https://github.com/WordPress/twentytwenty/blob/master/style.css#L365

```css
@font-face {
	font-family: "Inter var";
	font-weight: 100 900;
	font-style: normal;
	font-named-instance: "Regular";
	src: url(./assets/fonts/inter/Inter-upright.var.woff2) format("woff2");
}
```

• `373:2   ✖  Unexpected unknown property    property-no-unknown "font-named-instance"`

https://github.com/WordPress/twentytwenty/blob/master/style.css#L373

```css
@font-face {
	font-family: "Inter var";
	font-weight: 100 900;
	font-style: italic;
	font-named-instance: "Italic";
	src: url(./assets/fonts/inter/Inter-italic.var.woff2) format("woff2");
}
```
